### ISSUE TITLE
Build on CentOS 7.6

### ISSUE THREAD

**Issue by kogdenko** [Juniper/warp17#112]
Hi!
Trying to build warp17 on centos7.6. Compilation failed:
```bash
tpg_rpc.c:265:5: error: implicit declaration of function ‘protobuf_c_dispatch_default’
```
I get protobuf-c-rpc from https://github.com/protobuf-c/protobuf-c-rpc
What I am doing wrong?

**Comment by davvore33** [comment]
Hi @kogdenko ,

Can I ask you the results of those two commands?
```
$ protoc --version
$ protoc-c --version
```
Many Thanks

**Comment by kogdenko** [comment]
```bash
$ protoc --version
libprotoc 2.5.0
$ protoc-c --version
protobuf-c 1.0.2
libprotoc 2.5.0
```

**Comment by davvore33** [comment]
Ok @kogdenko , this is what I got
```
$ protoc --version
libprotoc 2.6.1
$ protoc-c --version
libprotoc 2.5.0
```
I'm not sure how this can affect, I'll try to install it on CentOS on my own today, brb

**Comment by davvore33** [comment]
@kogdenko Sorry to bother you but I'm having problems compiling protoc over there, can you please provide the steps you had to do?

**Comment by kogdenko** [comment]
Hello
```bash
git clone https://github.com/protobuf-c/protobuf-c-rpc
cd protobuf-c-rpc
./autogen.sh
./configure
make
```

**Comment by davvore33** [comment]
for some reason when I try to compile and install https://github.com/protocolbuffers/protobuf/tree/2.6.1-artifacts than protobuf-c doesn't find it

**Comment by dceara** [comment]
The installation procedure should probably be changed to install from sources from https://github.com/protobuf-c/protobuf-c-rpc instead of downloading unsigned packages. This probably requires some changes in tpg_rpc.c indeed to use the new `protobuf_c_rpc_dispatch_default`/`protobuf_c_rpc_dispatch_add_idle`/`protobuf_c_rpc_dispatch_run` APIs instead of the old `protobuf_c_dispatch_default`/`protobuf_c_dispatch_add_idle`/`protobuf_c_dispatch_run`.

@davvore33 what do you think?

**Comment by davvore33** [comment]
@dceara I guess we should at this point update the whole project to protobuf 3, it shouldn't be a huge amount of work anyway, I've never had the chance to look too much into it but for what i got they split the project in two parts

**Comment by dceara** [comment]
@kogdenko, @davvore33, for CentOS 7.6 I managed to get Warp17 up and running with the following changes (still WIP):

https://github.com/dceara/warp17/commit/7cfedb128987d13b82602fe51120956f980de661
