### ISSUE TITLE
Compile errors in 1.8

### ISSUE THREAD

**Issue by ck-9000** [Juniper/warp17#89]
Compiling on Ubuntu 14.04.5. Followed instructions/prerequisites found on https://github.com/Juniper/warp17.

root@ubuntu:~/warp17-1.8# make
make[1]: Entering directory `/root/warp17-1.8/api'
  PC-C warp17-common.proto
  PC-PY warp17-common.proto
  PC-XLATE warp17-common.proto
  PC-C warp17-l3.proto
  PC-PY warp17-l3.proto
  PC-XLATE warp17-l3.proto
  PC-C warp17-app-raw.proto
  PC-PY warp17-app-raw.proto
  PC-XLATE warp17-app-raw.proto
  PC-C warp17-app-http.proto
  PC-PY warp17-app-http.proto
  PC-XLATE warp17-app-http.proto
  PC-C warp17-app.proto
  PC-PY warp17-app.proto
  PC-XLATE warp17-app.proto
  PC-C warp17-client.proto
  PC-PY warp17-client.proto
  PC-XLATE warp17-client.proto
  PC-C warp17-server.proto
  PC-PY warp17-server.proto
  PC-XLATE warp17-server.proto
  PC-C warp17-test-case.proto
  PC-PY warp17-test-case.proto
  PC-XLATE warp17-test-case.proto
  PC-C warp17-sockopt.proto
  PC-PY warp17-sockopt.proto
  PC-XLATE warp17-sockopt.proto
  PC-C warp17-stats.proto
  PC-PY warp17-stats.proto
  PC-XLATE warp17-stats.proto
  PC-C warp17-service.proto
  PC-PY warp17-service.proto
  PC-XLATE warp17-service.proto
make[1]: Leaving directory `/root/warp17-1.8/api'
make[1]: Entering directory `/root/warp17-1.8'
  CC tpg_arp.o
In file included from /root/warp17-1.8/src/tpg_arp.c:75:0:
/root/warp17-1.8/inc/tcp_generator.h:108:0: error: "container_of" redefined [-Werror]
 #define container_of(ptr, type, member) \
 ^
In file included from /usr/local/share/dpdk/x86_64-native-linuxapp-gcc/include/rte_memcpy.h:47:0,
                 from /usr/local/share/dpdk/x86_64-native-linuxapp-gcc/include/rte_ether.h:50,
                 from /usr/local/share/dpdk/x86_64-native-linuxapp-gcc/include/rte_arp.h:42,
                 from /root/warp17-1.8/src/tpg_arp.c:73:
/usr/local/share/dpdk/x86_64-native-linuxapp-gcc/include/rte_common.h:392:0: note: this is the location of the previous definition
 #define container_of(ptr, type, member) __extension__ ({  \
 ^
In file included from /root/warp17-1.8/inc/tcp_generator.h:194:0,
                 from /root/warp17-1.8/src/tpg_arp.c:75:
/root/warp17-1.8/inc/tpg_lookup.h: In function ‘tlkp_alloc_cb_init’:
/root/warp17-1.8/inc/tpg_lookup.h:404:9: error: ‘rte_mempool_virt2phy’ is deprecated (declared at /usr/local/share/dpdk/x86_64-native-linuxapp-gcc/include/rte_mempool.h:1485) [-Werror=deprecated-declarations]
         rte_mempool_virt2phy(mp, container) + offset_in_container;
         ^
cc1: all warnings being treated as errors
make[2]: *** [tpg_arp.o] Error 1
make[1]: *** [all] Error 2
make[1]: Leaving directory `/root/warp17-1.8'
make: *** [all] Error 2

**Comment by dceara** [comment]
@ck-9000 Looks to me like you're trying to compile v1.8 of Warp17 with the instructions of the dev/common branch (latest). The dev/common branch uses a newer version of DPDK (17.11.3) while v1.8 works with DPDK 16.11.2.

Please follow the [instructions on the master branch (v1.8)](https://github.com/Juniper/warp17/tree/master). It should fix your issue.

We'll be releasing v1.9 at some point soon and then the supported DPDK version will be DPDK 17.11.3.
